spring.application.name=cafeteria


spring.datasource.url=jdbc:postgresql://localhost/cafeteria
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true